### ISSUE TITLE
Thunderstore Modpack Support

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [returnkirbo/Lethal-Company-Modpack#1]
Hi!

First off, this is a nice improvement to my scripts, thanks for releasing it to the community.

Anyhow, this is a request to support thunderstore modpacks - they can be exported to a code, why not let your script take these modpack codes as an argument?

**Comment by iamnotbobby** [comment]
supported now! it should read off a modpack's ``manifest.json`` with support for additional mods

i also appreciate you for checking out the repo. powershell scripting is still relatively new to me so part of your code was pretty much a learning experience for me :)
