### ISSUE TITLE
Soft Security Issue

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [returnkirbo/Lethal-Company-Modpack#2]
There is a security issue here, you can replace the script without changing the url.

There are two good options to fix it:

1) Don't do publishes, instead advertise your url using the direct github link. e.g. `https://raw.githubusercontent.com/returnkirbo/Lethal-Company-Modpack/ef6d80b6461762d4fad168332ead5e733a6af81e/InstallScript.ps1`

2) Sign your scripts before publishing.
The second option means you have a 'base' script that is commit-locked, this script downloads the latest publish, and checks if you have signed it using your private key. This enables you to auto-update in the future without as many security concerns.

Full disclaimer, I haven't done this yet, simply because I didn't plan on maintaining my scripts long term. It was pretty much just to reduce the modding support channels in the early days of lc modding.

**Comment by iamnotbobby** [comment]
thanks, i was actually going to do this at one point but forgot. i've replaced all mentions of any link with the proper [link](https://raw.githubusercontent.com/returnkirbo/Lethal-Company-Modpack/main/Install-Modpack.ps1)

**Comment by KrystilizeNevaDies** [comment]
> thanks, i was actually going to do this at one point but forgot. i've replaced all mentions of any link with the proper [link](https://raw.githubusercontent.com/returnkirbo/Lethal-Company-Modpack/main/Install-Modpack.ps1)

This link also has the same issues as mentioned above.

**Comment by iamnotbobby** [comment]
link mentions in the project's README should be updated to use a commit-locked url now
